CXX = mpicxx
CXXFLAGS = -O3 -I. 

all: example1 example2

example1: Example\ MNIST/example1.cpp
	$(CXX) $(CXXFLAGS) -o example1 Example\ MNIST/example1.cpp

example2: Example\ MNIST/example2.cpp
	$(CXX) $(CXXFLAGS) -o example2 Example\ MNIST/example2.cpp
